# Generated by Django 5.1 on 2025-09-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('cash', 'Cash on Delivery'), ('paypal', 'PayPal')], max_length=50),
        ),
    ]
